# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 738e4c06b717c12ced12ec663a196f512c4be94bc715454dd2303ee91101c41e7e312bba6b3db04936a303ae19b0c1817d569e640d4825afb9c414814ee8220a

test:
  secret_key_base: 6db6d7dd27f2f45458370b29d613da66200d694a25b86dc7065f4368fe4f250293e152d4cae4a9144e24692852096c60b51385b5e6bf4a4c1497291c073b9df0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
